config/routes.rb
Rails.application.routes.draw do
  get 'posts/new'
  post 'posts/create'
  get 'posts/index'
  root 'posts#index'
  get 'posts/dashboard'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence:true
  validates :image_url, presence:true
  validates :content, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  http_basic_authenticate_with name: "desafiovamoscontodo", password: "XAHTJEAS23123%23", except: :index
  def new
    @post = Post.new
  end

  def create
    @post =Post.create(title: params[:post][:title], 
                date: params[:post][:date],
                image_url: params[:post][:image_url],
                content: params[:post][:content])
    
  end
  def index
    @posts = Post.all
  end

  def dashboard


    @posts = Post.all

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApiBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model:@post, url: posts_create_path do |f| %>
  <%= f.text_field :title %>
  <%= f.text_field :image_url %>
  <%= f.text_area :content %>
  <%= f.submit 'save' %>
<% end %> 

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/dashboard.html.erb
<%= render 'form', tweet: @tweet %>

<table class = "table">
  <thead>
    <tr>
      <th> Title </th>
      <th> Date </th>
      <th> Image Url </th>
      <th> Content </th>
    </tr>
  </thead>
  <tbody>
    <% @posts.reverse.each do |post| %>
    <tr>
    <td><%= post.title %></td>
    <td><%= post.date %></td>
    <td><%= post.image_url %></td>
    <td><%= post.content %></td>
    <tr>
    <% end %>
  </tbody>
</table>

app/views/posts/index.html.erb
<table class = "table">
  <thead>
    <tr>
      <th> Title </th>
      <th> Date </th>
      <th> Image Url </th>
      <th> Content </th>
    </tr>
  </thead>
  <tbody>
    <% @posts.reverse.each do |post| %>
    <tr>
    <td><%= post.title %></td>
    <td><%= post.date %></td>
    <td><%= post.image_url %></td>
    <td><%= post.content %></td>
    <tr>
    <% end %>
  </tbody>
</table>

app/views/posts/new.html.erb
<h1>Posts#new</h1>

<!-- app/views/posts/new.html.erb-->
<%= form_with model:@post, url: posts_create_path do |f| %>
  <%= f.text_field :title %>
  <%= f.date_field :date %>
  <%= f.text_field :image_url %>
  <%= f.text_area :content %>
  <%= f.submit 'save' %>
<% end %> 